### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by p-soham11** [yalematta/hack-the-coding-interview-this-october#3]
Sorting Algos are missing. Can I work on Bubble, Selection and Insertion sort ? 
Language : C++

**Comment by yalematta** [comment]
Thank you Soham for your contribution!
Please check the daily added folders, they contain each a problem that you can contribute your solution to.

To contribute your sorting algorithms, please use the same technique in [this problem](https://github.com/yalematta/hack-the-coding-interview-this-october/blob/master/01-10-20/LongestSubstring.md). State the problem you're trying to solve, give an example with the input and expected output then share your code solution as well as the time and space complexity. 

Happy hacking!
